#!/usr/bin/env node

const { discoverGateway, TradfriClient } = require('node-tradfri-client');

Promise.resolve()
  .then(() => console.log('discoverGateway()'))
  .then(() => discoverGateway())
  .then(res => console.log(res) || res)
  .then(res => {
    if (process.argv[2]) {
      console.log(`authenticate()`);
      const tradfri = new TradfriClient(res.addresses[0]);
      return tradfri
        .authenticate(process.argv[2])
        .then(res => console.log(res) || res)
        .then(() => console.log('Done, Ctrl + C to exit'));
    } else {
      console.log('To authenticate, run again with your Trådfri security code as argument');
    }
  })

  .catch(err => console.log(err));
