#!/bin/sh
set -eu

# Egress policy for the dev container.
#
# This container owns the network namespace and the dev container joins it
# (`network_mode: service:net`), so these rules govern the dev container's
# outbound traffic. It has no NET_ADMIN, so it cannot alter them.
#
# Ownership is this way round on purpose: recreating the dev container rejoins a
# namespace that still has these rules. Were it the owner, every rebuild would
# hand it a fresh, empty, default-ACCEPT namespace instead.
#
# Two modes, set by EGRESS in dev/claude/.env:
#
#   allowlist (default)  deny everything outbound except the domains below, the
#                        Home Assistant instance, and loopback
#   any                  no firewall at all -- including reachability of the
#                        HOST machine, so every service you have bound to a
#                        localhost port is exposed to whatever runs in here
#
# Changing the mode changes this container's environment, so compose recreates
# it; bin/claude then repairs the stranded dev container.
#
# Fail-closed: in allowlist mode the policy is DROP before any accept is added,
# and everything needed is baked into the image, so a script that dies partway
# leaves the container with no egress rather than full access.

EGRESS="${EGRESS:-allowlist}"
HA_HOST_IP="${HA_HOST_IP:?set HA_HOST_IP in dev/claude/.env}"
HA_PORT="${HA_PORT:-8123}"

# What the box may reach by name in allowlist mode.
#
# Anthropic's own hosts, per
# https://code.claude.com/docs/en/network-config#network-access-requirements --
# api.anthropic.com is inference, statsig is feature flags, platform is OAuth
# token refresh (a setup-token credential still refreshes), downloads is the
# auto-updater.
#
# github/npm are here because without them the container cannot bootstrap
# itself: bin/claude clones on first run, and the frontend needs `npm ci`.
#
# The docs hosts earn their place: checking Home Assistant's own source and docs
# is how several wrong API calls were caught in this project (a view attribute
# that does nothing, two accessors removed or renamed in later HA versions).
# raw.githubusercontent.com is how HA's source gets read directly.
#
# Deliberately absent: both Datadog telemetry intakes and any org-managed OTEL
# collector. Managed settings sit at the top of Claude Code's precedence chain
# and can be delivered server-side, so an env var is a request while a firewall
# rule is a fact.
ALLOWED_DOMAINS="
api.anthropic.com
statsig.anthropic.com
platform.claude.com
downloads.claude.ai
github.com
codeload.github.com
raw.githubusercontent.com
registry.npmjs.org
developers.home-assistant.io
www.home-assistant.io
"

SET4=allowed4
SET_TIMEOUT=86400 # 24h -- see the note in configure_dns()

DNS_LISTEN=127.0.0.1  # where dnsmasq listens; the dev container shares this netns
DNS_UPSTREAM=127.0.0.11 # Docker's embedded resolver, on loopback in-netns

reset_rules() {
  iptables -F OUTPUT
  iptables -P OUTPUT ACCEPT
  ip6tables -F OUTPUT
  ip6tables -P OUTPUT ACCEPT
}

# dnsmasq becomes the only resolver for the namespace, and adds each resolved
# address of an allowlisted domain to $SET4 *as it answers the query* -- so the
# address the box is about to dial is permitted by the time it connects. A
# resolve-once-at-startup snapshot would go stale against CDN rotation and fail
# silently, which is the whole reason for doing it this way.
#
# The 24h set timeout is long on purpose: entries are only re-added on a cache
# *miss*, so a short timeout would expire an address that dnsmasq still has
# cached and silently break a long-running session.
configure_dns() {
  domains=$(echo "$ALLOWED_DOMAINS" | tr -s '[:space:]' '/' | sed 's|^/||; s|/$||')

  cat > /etc/dnsmasq.conf <<EOF
# Generated by firewall.sh -- do not edit.
listen-address=$DNS_LISTEN
bind-interfaces
no-resolv
no-hosts
server=$DNS_UPSTREAM
ipset=/$domains/$SET4
EOF

  dnsmasq --conf-file=/etc/dnsmasq.conf

  # Shared with the dev container, so this points the whole namespace at
  # dnsmasq. No 127.0.0.11 fallback: a fallback would resolve *around* dnsmasq
  # and never populate the allow-set.
  printf 'nameserver %s\noptions ndots:0\n' "$DNS_LISTEN" > /etc/resolv.conf
}

apply_allowlist() {
  ipset destroy "$SET4" 2>/dev/null || true
  ipset create "$SET4" hash:ip timeout "$SET_TIMEOUT"

  iptables -F OUTPUT
  iptables -P OUTPUT DROP
  iptables -A OUTPUT -o lo -j ACCEPT
  iptables -A OUTPUT -d 127.0.0.0/8 -j ACCEPT # dnsmasq, and its upstream
  iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  # Home Assistant: a LAN address that is never resolved, so it's a targeted
  # hole rather than an allowlisted domain.
  iptables -A OUTPUT -d "$HA_HOST_IP" -p tcp --dport "$HA_PORT" -j ACCEPT
  iptables -A OUTPUT -m set --match-set "$SET4" dst -p tcp -m multiport --dports 80,443 -j ACCEPT
  # Reject rather than drop, so a blocked connection fails immediately instead
  # of hanging until something times out.
  iptables -A OUTPUT -p tcp -j REJECT --reject-with tcp-reset
  iptables -A OUTPUT -j REJECT

  # No IPv6 egress at all. Nothing we allow is v6-only, and the allow-set is v4;
  # leaving v6 open would route straight around the allowlist.
  ip6tables -F OUTPUT
  ip6tables -P OUTPUT DROP
  ip6tables -A OUTPUT -o lo -j ACCEPT
  ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  ip6tables -A OUTPUT -j REJECT
}

case "$EGRESS" in
  any)
    reset_rules
    echo "firewall: EGRESS=any -- NO restrictions."
    echo "firewall: the dev container can now reach the internet, your LAN, AND"
    echo "firewall: your host machine, including anything bound to a localhost"
    echo "firewall: port that assumes localhost means trusted."
    ;;
  allowlist)
    apply_allowlist
    configure_dns
    echo "firewall: EGRESS=allowlist"
    echo "firewall: Home Assistant at ${HA_HOST_IP}:${HA_PORT}"
    echo "firewall: allowed by name:" $ALLOWED_DOMAINS
    ;;
  *)
    echo "firewall: unknown EGRESS='$EGRESS' (expected 'allowlist' or 'any')" >&2
    exit 1
    ;;
esac

echo "firewall: rules applied ------------------------------------------"
iptables -S OUTPUT
echo "------------------------------------------------------------------"

# Stay alive: this container owns the namespace the dev container is using, so
# it must outlive it. Recreating *this* container is the one operation that
# requires recreating the dev container too.
exec tail -f /dev/null
